### ISSUE TITLE
连接主机报错，是否需要更新url?

### ISSUE THREAD

**Issue by jiangnan1132** [wangsongiam/sina-stock-crawler#2]
链接主机报错
Traceback (most recent call last):
  File "H:/cats/sina_data_service/sina-stock-crawler-master/main.py", line 96, in <module>
    date = get_expire_date(get_expire_url(date_string[:6]))
  File "H:/cats/sina_data_service/sina-stock-crawler-master/main.py", line 80, in get_expire_date
    with urllib.request.urlopen(url_link) as url:
  File "F:\soft\anaconda\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "F:\soft\anaconda\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "F:\soft\anaconda\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "F:\soft\anaconda\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "F:\soft\anaconda\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "F:\soft\anaconda\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "F:\soft\anaconda\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "F:\soft\anaconda\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "F:\soft\anaconda\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "F:\soft\anaconda\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by jiangnan1132** [comment]
原链接：http://stock.finance.sina.com.cn/futures/api/openapi.php/StockOptionService.getRemainderDay?date=201810

**Comment by wangsongiam** [comment]
刚试了一下，我在美国西海岸是没有timeout的。我建议你检查一下网络。
